name: Deploy

on:
  push:
    branches: [master]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build
        run: npm install && npm run build
        
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: bundle
          path: ./dist
          
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: bundle
          path: ./dist

      - name: Deploy with SSH
        uses: easingthemes/ssh-deploy@v2.1.4
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: "dist/"
          TARGET: "~/biblys.org"
